// <auto-generated />
using HepsiBurada.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HepsiBurada.Data.Migrations
{
    [DbContext(typeof(HepsiBuradaContext))]
    partial class HepsiBuradaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HepsiBurada.Data.Models.Campaign", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("PriceManipulationLimit")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProductsProductCode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TargetSalesCount")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("ProductsProductCode");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("HepsiBurada.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProductsProductCode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductsProductCode");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HepsiBurada.Data.Models.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HepsiBurada.Data.Models.Campaign", b =>
                {
                    b.HasOne("HepsiBurada.Data.Models.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsProductCode");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("HepsiBurada.Data.Models.Order", b =>
                {
                    b.HasOne("HepsiBurada.Data.Models.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsProductCode");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
